### ISSUE TITLE
2023-07-16 15:00 cpu 급증 후 서버죽음

### ISSUE THREAD

**Issue by seungyeonchoi** [sullog-official/sullog-server#141]
![image](https://github.com/sullog-official/sullog-server/assets/48347010/4b360315-77f1-4f0a-9b5e-b7f627f1efad)

# 알파서버
<details>
<summary> 로그보기 </summary>
15시 직전 요청이 04시라서... 04시 요청은 연관성 없어보임 ..

```
ESC[36m2023-07-16 04:05:24.720ESC[m ESC[32m[INFO ]ESC[m [org.apache.juli.logging.DirectJDKLog] ESC[33m[http-nio-8082-exec-8]ESC[m- Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x030x000x00/*0xe00x000x000x000x000x00Cookie: ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
ESC[36m2023-07-16 15:04:55.458ESC[m ESC[32m[INFO ]ESC[m [com.zaxxer.hikari.HikariDataSource] ESC[33m[SpringApplicationShutdownHook]ESC[m- HikariPool-1 - Shutdown initiated...
ESC[36m2023-07-16 15:04:55.477ESC[m ESC[32m[INFO ]ESC[m [com.zaxxer.hikari.HikariDataSource] ESC[33m[SpringApplicationShutdownHook]ESC[m- HikariPool-1 - Shutdown completed.
ESC[36m2023-07-16 15:05:08.297ESC[m ESC[32m[INFO ]ESC[m [org.springframework.boot.StartupInfoLogger] ESC[33m[main]ESC[m- Starting BackendApplication using Java 17.0.7 on ip-172-31-36-86 with PID 41727 (/home/ubuntu/deploy/backend-0.0.1-SNAPSHOT.jar started by ubuntu in /home/ubuntu
/deploy/wasControl)
ESC[36m2023-07-16 15:05:08.338ESC[m ESC[32m[INFO ]ESC[m [org.springframework.boot.SpringApplication] ESC[33m[main]ESC[m- The following 4 profiles are active: "jwt", "aws", "mybatis", "alpha"
ESC[36m2023-07-16 15:05:14.518ESC[m ESC[33m[WARN ]ESC[m [com.amazonaws.util.EC2MetadataUtils] ESC[33m[main]ESC[m- Unable to retrieve the requested metadata (/latest/user-data/). The requested metadata is not found at http://169.254.169.254/latest/user-data/
com.amazonaws.SdkClientException: The requested metadata is not found at http://169.254.169.254/latest/user-data/
        at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:89) ~[aws-java-sdk-core-1.11.792.jar!/:?]
        at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70) ~[aws-java-sdk-core-1.11.792.jar!/:?]
        at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75) ~[aws-java-sdk-core-1.11.792.jar!/:?]
        at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66) ~[aws-java-sdk-core-1.11.792.jar!/:?]
        at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:402) ~[aws-java-sdk-core-1.11.792.jar!/:?]
        at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:371) ~[aws-java-sdk-core-1.11.792.jar!/:?]
        at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:367) ~[aws-java-sdk-core-1.11.792.jar!/:?]
        at com.amazonaws.util.EC2MetadataUtils.getUserData(EC2MetadataUtils.java:363) ~[aws-java-sdk-core-1.11.792.jar!/:?]
        at org.springframework.cloud.aws.core.env.ec2.AmazonEc2InstanceDataPropertySource.getUserData(AmazonEc2InstanceDataPropertySource.java:123) ~[spring-cloud-aws-core-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.cloud.aws.core.env.ec2.AmazonEc2InstanceDataPropertySource.getProperty(AmazonEc2InstanceDataPropertySource.java:95) ~[spring-cloud-aws-core-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
        at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85) ~[spring-core-5.3.25.jar!/:5.3.25]
        at org.springframework.core.env.PropertySourcesPropertyResolver.getPropertyAsRawString(PropertySourcesPropertyResolver.java:74) ~[spring-core-5.3.25.jar!/:5.3.25]
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:153) ~[spring-core-5.3.25.jar!/:5.3.25]
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126) ~[spring-core-5.3.25.jar!/:5.3.25]
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.3.25.jar!/:5.3.25]
```

</details> 

# 리얼서버

<details>
<summary> 로그보기 </summary>

```
2023-07-16 14:56:56.739 ERROR 31024 --- [nio-8081-exec-3] s.b.c.e.CommonControllerAdvice           : 미처리 예외 발생

org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
        at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:260) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:442) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:383) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:125) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:67) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:498) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.DispatcherServlet.getHandler(DispatcherServlet.java:1265) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1047) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:696) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at sullog.backend.member.config.jwt.JwtAuthFilter.doFilterInternal(JwtAuthFilter.java:35) ~[classes!/:?]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:178) ~[spring-security-oauth2-client-5.7.6.jar!/:5.7.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.7.6.jar!/:5.7.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar!/:5.3.25]
```

문제의 15시 이후...  뭔가 미심쩍은 로그가 있음
```
2023-07-16 15:09:00.381  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m37s999ms834µs844ns).
2023-07-16 15:10:07.275  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m4s164ms397µs172ns).
2023-07-16 15:18:26.548  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=53s562ms755µs995ns).
2023-07-16 15:19:32.235  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m14s817ms297µs77ns).
2023-07-16 15:20:29.151  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=54s361ms285µs844ns).
2023-07-16 15:21:27.029  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m1s323ms44µs599ns).
2023-07-16 15:22:12.273  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=48s61ms803µs282ns).
2023-07-16 15:23:07.259  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=51s778ms661µs653ns).
2023-07-16 15:23:57.393  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=53s327ms240µs497ns).
2023-07-16 15:25:05.125  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=46s930ms578µs37ns).
2023-07-16 15:25:50.937  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m6s240ms642µs184ns).
2023-07-16 15:27:03.871  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m12s522ms321µs189ns).
2023-07-16 15:27:51.849  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=46s131ms972µs784ns).
2023-07-16 15:28:38.161  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=49s516ms849µs365ns).
2023-07-16 15:39:19.044  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m23s425ms702µs422ns).
2023-07-16 15:41:38.368  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m4s230ms932µs617ns).
2023-07-16 15:42:43.457  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=2m19s289ms320µs618ns).
2023-07-16 15:44:38.370  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m3s298ms834µs694ns).
2023-07-16 15:45:57.324  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=2m13s49ms273µs970ns).
2023-07-16 15:48:53.118  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m2s944ms374ns).
2023-07-16 15:50:03.392  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=2m59s575ms910µs931ns).
2023-07-16 15:51:31.474  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m19s790ms829µs903ns).
2023-07-16 15:53:04.614  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m48s91ms422µs473ns).
2023-07-16 15:54:06.935  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=59s589ms281µs794ns).
2023-07-16 15:55:04.529  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=59s87ms836µs723ns).
2023-07-16 15:56:12.238  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=58s792ms477µs568ns).
2023-07-16 15:57:20.429  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m15s127ms236µs665ns).
2023-07-16 15:58:29.039  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m7s117ms928µs173ns).
2023-07-16 15:59:31.082  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m458ms122µs430ns).
2023-07-16 16:00:36.884  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m13s239ms529µs929ns).
2023-07-16 16:01:32.161  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=51s788ms152µs301ns).
2023-07-16 16:04:10.443  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=2m43s784ms528µs294ns).
2023-07-16 16:05:11.926  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=58s864ms233µs424ns).
2023-07-16 16:06:07.367  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=50s704ms955µs258ns).
2023-07-16 16:07:02.793  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=54s259ms233µs577ns).
2023-07-16 16:07:56.451  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m1s207ms511µs839ns).
2023-07-16 16:08:57.414  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=57s615ms917µs54ns).
2023-07-16 16:09:57.430  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m511ms663µs774ns).
2023-07-16 16:11:12.842  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m12s890ms865µs826ns).
2023-07-16 16:12:55.277  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m37s77ms620µs765ns).
2023-07-16 16:17:02.261  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=4m10s394ms886µs513ns).
2023-07-16 16:21:02.557  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m9s287ms949µs27ns).
2023-07-16 16:25:08.078  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=5m5s862ms87µs930ns).
2023-07-16 16:26:21.221  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=2m55s833ms299µs764ns).
2023-07-16 16:29:47.443  WARN 31024 --- [l-1 housekeeper] c.z.h.p.HikariPool                       : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m12s907ms952µs560ns).
nohup: ignoring input
```

익일 새벽4시에 재시작된 로그도 !? 16일 15시 요청 영향은 아닌것으로 보임
```
2023-07-17 04:14:44.532  INFO 1359 --- [           main] s.b.BackendApplication                   : Starting BackendApplication using Java 17.0.7 on ip-172-31-36-86 with PID 1359 (/home/ubuntu/deploy/backend-0.0.1-SNAPSHOT.jar started by ubuntu in /home/ubuntu/deploy)
2023-07-17 04:14:44.553  INFO 1359 --- [           main] s.b.BackendApplication                   : The following 4 profiles are active: "jwt", "aws", "mybatis", "live"
2023-07-17 04:14:47.941  WARN 1359 --- [           main] c.a.u.EC2MetadataUtils                   : Unable to retrieve the requested metadata (/latest/user-data/). The requested metadata is not found at http://169.254.169.254/latest/user-data/

```

</details>

**Comment by seungyeonchoi** [comment]
서버는 utc 기준으로 로그가 찍혀서, +9 기준으로 다시 로그 살펴봐야함

**Comment by seungyeonchoi** [comment]
서버가 그냥 죽음.. .. . 
- 인스턴스 재시작 후 서버 다시 띄움
